### PR TITLE
Change Label to Focus and Stop

### PR DESCRIPTION
**Pull request by ikrydev**
Reference for this issue #10

### CODE REVIEW

**Comment by ikrydev** [comment]
For #18 and #7

**Review by karimdaghari — CHANGES_REQUESTED** [review]
Thank you! However, in order for the app to build, the version has to be bumped. The only thing left for you to do is to bump the version from 1.4.1 to 1.4.3 (in package.json). Once you do that, I’ll gladly merge your PR.

**Comment by ikrydev** [comment]
Done @kdaghari

**Comment by karimdaghari** [comment]
@ikrydev Your PR was successfully merged. I know that this is a pretty small and (relatively speaking) insignificant project however, congrats on making an everlasting impact on it. With that said, I'd like to give you a two tips in regards to git/hub (that I hope will help you going forward):

- **One branch. One thing.** Any branch you create should be focused on doing one thing and one thing only. (The Unix philosophy: do one thing and do it well).
- Branch names should always be prefixed with either **feat** (if you're adding/bettering(refactoring) something) or **hotfix** (if you're fixing a bug)

**Comment by ikrydev** [comment]
@kdaghari Cool... thanks for your advice... ^_^

**Pull request merged**
